# Generated by Django 3.2.5 on 2021-08-01 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='address',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='place',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
